name: BlockGrid
version: 1.0
main: com.markegli.bukkit.blockgrid.BlockGridPlugin
load: STARTUP
author: markegli
authors: [LRFLEW, sethbling]
description: Allows the server to generate SkyGrid-like worlds